### PR TITLE
#to_si should be a non-destructive operation

### PR DESCRIPTION
**Pull request by cblock**
Andrew,

I sincerely apologize for this  careless mistake introduced in my previous pull request. At least it had bitten me quickly...

Cheers,
Carsten

### CODE REVIEW

**Comment by spatchcock** [comment]
Hey Carsten. No problem! Just one thought - I am not sure if #clone would be better than #dup? Unit objects are cloned frequently and there are specific initialize_copy methods defined on each associated class (base unit, compound units, etc). There is no initialize_copy on Quantity, but if we are cloning Quantity instances I think it would be good practice to make it a deep clone so that unit instances are not referenced by more than one quantity instance. Any thoughts?

**Comment by cblock** [comment]
That sounds very reasonable to me.

**Comment by spatchcock** [comment]
Okay - I'll do that tonight, should be straightforward. Cheers.

**Comment by spatchcock** [comment]
Done! Turns out #dup and #clone both make use of #initialize_copy when defined.

**Comment by cblock** [comment]
...cool. Thanks!

**Pull request merged**
